In [22]:
import pandas as pd

In [23]:
DATA = 'https://raw.githubusercontent.com/rafabandoni/world-cup-2026-predict/refs/heads/main/data/'

In [28]:
elo = pd.read_csv(DATA+'elo_ratings_wc2026.csv')
elo.head()

,year,snapshot_date,country,rank,country_code,rating,rank_max,rating_max,rank_avg,rating_avg,...,matches_home,matches_away,matches_neutral,wins,losses,draws,goals_for,goals_against,confederation,is_host
0,1901,1901-12-31,England,1,EN,2013,1,2079,2,1989,...,38,35,0,46,16,11,262,102,UEFA,0
1,1901,1901-12-31,Scotland,2,SQ,1973,1,2104,1,2018,...,37,37,0,53,9,12,277,101,UEFA,0
2,1902,1902-12-31,Argentina,1,AR,2021,1,2021,1,2021,...,0,1,0,1,0,0,6,0,CONMEBOL,0
3,1902,1902-12-31,England,2,EN,1995,1,2079,2,1989,...,39,38,0,47,16,14,266,105,UEFA,0
4,1902,1902-12-31,Scotland,3,SQ,1983,1,2104,1,2017,...,39,40,0,56,9,14,293,106,UEFA,0

In [30]:
matches_hist = pd.read_csv(DATA+'world_cup_matches.csv')
matches_hist.head()

,ID,Year,Date,Stage,Home Team,Home Goals,Away Goals,Away Team,Win Conditions,Host Team
0,1,1930,1930-07-13,Group stage,France,4,1,Mexico,NaN,False
1,2,1930,1930-07-13,Group stage,United States,3,0,Belgium,NaN,False
2,3,1930,1930-07-14,Group stage,Yugoslavia,2,1,Brazil,NaN,False
3,4,1930,1930-07-14,Group stage,Romania,3,1,Peru,NaN,False
4,5,1930,1930-07-15,Group stage,Argentina,1,0,France,NaN,False

In [27]:
data[data['country']=='England']

,year,snapshot_date,country,rank,country_code,rating,rank_max,rating_max,rank_avg,rating_avg,...,matches_home,matches_away,matches_neutral,wins,losses,draws,goals_for,goals_against,confederation,is_host
0,1901,1901-12-31,England,1,EN,2013,1,2079,2,1989,...,38,35,0,46,16,11,262,102,UEFA,0
3,1902,1902-12-31,England,2,EN,1995,1,2079,2,1989,...,39,38,0,47,16,14,266,105,UEFA,0
8,1903,1903-12-31,England,2,EN,1968,1,2079,2,1989,...,42,38,0,49,17,14,273,108,UEFA,0
13,1904,1904-12-31,England,2,EN,1981,1,2079,2,1988,...,42,41,0,51,17,15,279,111,UEFA,0
20,1905,1905-12-31,England,2,EN,1973,1,2079,2,1988,...,45,41,0,53,17,16,284,113,UEFA,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4447,2023,2023-12-31,England,5,EN,2014,1,2213,4,1983,...,494,518,119,665,209,257,2663,1100,UEFA,0
4494,2024,2024-12-31,England,4,EN,2006,1,2213,4,1983,...,501,521,126,674,213,261,2692,1113,UEFA,0
4542,2025,2025-12-31,England,4,EN,2042,1,2213,4,1983,...,507,524,127,683,214,261,2718,1116,UEFA,0
4590,2026,2026-12-31,England,4,EN,2020,1,2213,4,1983,...,509,524,127,683,215,262,2719,1118,UEFA,0
4638,2026,2026-05-27,England,4,EN,2020,1,2213,4,1983,...,509,524,127,683,215,262,2719,1118,UEFA,0